name: .NET
on: [push, pull_request]

jobs:
  compile-native:
    name: Compile native libraries
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: cd native && ./build.sh

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: native-libraries
          path: native/bin/**/*

  build:
    name: .NET Build
    runs-on: ubuntu-22.04
    needs: compile-native
    steps:
      - uses: actions/checkout@v4

      - name: Download native libraries
        uses: actions/download-artifact@v4
        with:
          name: native-libraries
          path: native/bin

      - name: Update plugins.toml
        run: ./PluginManager.fsx update
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
